version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: search_agent_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    container_name: search_agent_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Qdrant внутри docker-сети
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_SOURCES_COLLECTION=sources

      # Ollama НА ХОСТЕ (Mac/Windows работает)
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen2.5:3b
    depends_on:
      - qdrant

  init_sources:
    container_name: search_agent_init_sources
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_SOURCES_COLLECTION=sources
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      - qdrant
    command: ["python", "-m", "src.rag.init_sources"]
    restart: "no"

volumes:
  qdrant_storage:
